# Generated by Django 4.1 on 2022-09-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crossing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('jurisdiction', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0, null=0)),
                ('comment', models.TextField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
