# Generated by Django 4.1 on 2022-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_camera_alter_crossing_lon_alter_crossing_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
