# Generated by Django 4.1 on 2022-09-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_camera_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='camera',
        ),
    ]
