# Generated by Django 4.1 on 2022-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_remove_image_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='camera_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
