# Generated by Django 4.1 on 2022-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_image_camera_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
